<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `ecm_my_mibao`;");
E_C("CREATE TABLE `ecm_my_mibao` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `mibao_sn` varchar(50) NOT NULL DEFAULT '0',
  `user_id` int(10) unsigned NOT NULL DEFAULT '0',
  `user_name` varchar(20) DEFAULT NULL,
  `admin_name` varchar(100) DEFAULT NULL,
  `add_time` int(8) unsigned NOT NULL DEFAULT '0',
  `bd_time` int(8) unsigned DEFAULT NULL,
  `dq_time` int(8) unsigned DEFAULT NULL,
  `ztai` int(3) unsigned NOT NULL DEFAULT '0',
  `A1` varchar(10) DEFAULT NULL,
  `B1` varchar(10) DEFAULT NULL,
  `C1` varchar(10) DEFAULT NULL,
  `D1` varchar(10) DEFAULT NULL,
  `E1` varchar(10) DEFAULT NULL,
  `F1` varchar(10) DEFAULT NULL,
  `G1` varchar(10) DEFAULT NULL,
  `H1` varchar(10) DEFAULT NULL,
  `A2` varchar(10) DEFAULT NULL,
  `B2` varchar(10) DEFAULT NULL,
  `C2` varchar(10) DEFAULT NULL,
  `D2` varchar(10) DEFAULT NULL,
  `E2` varchar(10) DEFAULT NULL,
  `F2` varchar(10) DEFAULT NULL,
  `G2` varchar(10) DEFAULT NULL,
  `H2` varchar(10) DEFAULT NULL,
  `A3` varchar(10) DEFAULT NULL,
  `B3` varchar(10) DEFAULT NULL,
  `C3` varchar(10) DEFAULT NULL,
  `D3` varchar(10) DEFAULT NULL,
  `E3` varchar(10) DEFAULT NULL,
  `F3` varchar(10) DEFAULT NULL,
  `G3` varchar(10) DEFAULT NULL,
  `H3` varchar(10) DEFAULT NULL,
  `A4` varchar(10) DEFAULT NULL,
  `B4` varchar(10) DEFAULT NULL,
  `C4` varchar(10) DEFAULT NULL,
  `D4` varchar(10) DEFAULT NULL,
  `E4` varchar(10) DEFAULT NULL,
  `F4` varchar(10) DEFAULT NULL,
  `G4` varchar(10) DEFAULT NULL,
  `H4` varchar(10) DEFAULT NULL,
  `A5` varchar(10) DEFAULT NULL,
  `B5` varchar(10) DEFAULT NULL,
  `C5` varchar(10) DEFAULT NULL,
  `D5` varchar(10) DEFAULT NULL,
  `E5` varchar(10) DEFAULT NULL,
  `F5` varchar(10) DEFAULT NULL,
  `G5` varchar(10) DEFAULT NULL,
  `H5` varchar(10) DEFAULT NULL,
  `A6` varchar(10) DEFAULT NULL,
  `B6` varchar(10) DEFAULT NULL,
  `C6` varchar(10) DEFAULT NULL,
  `D6` varchar(10) DEFAULT NULL,
  `E6` varchar(10) DEFAULT NULL,
  `F6` varchar(10) DEFAULT NULL,
  `G6` varchar(10) DEFAULT NULL,
  `H6` varchar(10) DEFAULT NULL,
  `A7` varchar(10) DEFAULT NULL,
  `B7` varchar(10) DEFAULT NULL,
  `C7` varchar(10) DEFAULT NULL,
  `D7` varchar(10) DEFAULT NULL,
  `E7` varchar(10) DEFAULT NULL,
  `F7` varchar(10) DEFAULT NULL,
  `G7` varchar(10) DEFAULT NULL,
  `H7` varchar(10) DEFAULT NULL,
  `A8` varchar(10) DEFAULT NULL,
  `B8` varchar(10) DEFAULT NULL,
  `C8` varchar(10) DEFAULT NULL,
  `D8` varchar(10) DEFAULT NULL,
  `E8` varchar(10) DEFAULT NULL,
  `F8` varchar(10) DEFAULT NULL,
  `G8` varchar(10) DEFAULT NULL,
  `H8` varchar(10) DEFAULT NULL,
  `A9` varchar(10) DEFAULT NULL,
  `B9` varchar(10) DEFAULT NULL,
  `C9` varchar(10) DEFAULT NULL,
  `D9` varchar(10) DEFAULT NULL,
  `E9` varchar(10) DEFAULT NULL,
  `F9` varchar(10) DEFAULT NULL,
  `G9` varchar(10) DEFAULT NULL,
  `H9` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8");

require("../../inc/footer.php");
?>